-- 1.Find total customers by countries

select country, count(customer_id) as total_customer
from dim_customers
group by country
order by total_customer desc;

-- 2.Find total customers by gender

select gender, count(customer_id) as total_customer
from dim_customers
group by gender
order by total_customer desc;

-- 3.Find total products by category

select category, count(product_id) as total_product
from dim_products
group by category
order by total_product desc;

-- 4.What is the average costs in each category?

select category, avg(cost) as average_costs
from dim_products
group by category
order by average_costs desc;

-- 5.What is the total revenue generated for each category?

select p.category as Category, sum(f.sales_amount) as Revenue
from fact_sales as f
left join dim_products as p
on f.product_key = p.product_key
group by p.category
order by Revenue desc;

-- 6.What is the total revenue generated by each customer?

select  c.customer_key,c.first_name,c.last_name, sum(f.sales_amount) as Revenue
from fact_sales as f
left join dim_customers as c
on f.customer_key = c.customer_key
group by c.customer_key,c.first_name,c.last_name
order by Revenue desc;


-- 7.What is the distribution of sold items across countries?

select c.country as Country, sum(f.quantity) as Sold_items
from fact_sales as f
left join dim_customers as c
on f.customer_key = c.customer_key
group by c.country
order by Sold_items desc;

